### ISSUE TITLE
Feature request: Keyboard shortcuts

### ISSUE THREAD

**Issue by Zeioth** [Benjioe/vscode-fold-unfold-all-icone#1]
Thank you for making this extension!
Would be really nice to be able to define keyboard shortcuts too.

**Comment by jumisingo** [comment]
You can attain this by following the VS Code keyboard shortcuts documentation:
https://code.visualstudio.com/docs/getstarted/keybindings#_basic-editing

To open the Keyboard Shortcut pallette: Ctrl+k+s

The commands you're looking for are:
-editor.foldAll
![image](https://user-images.githubusercontent.com/40045992/73299934-c0ff0780-41d5-11ea-9f08-440ad238461f.png)

-editor.unfoldAll
![image](https://user-images.githubusercontent.com/40045992/73299975-cf4d2380-41d5-11ea-9b20-5ffcdd1fdadd.png)
