### ISSUE TITLE
Folding levels

### ISSUE THREAD

**Issue by narkoze** [Benjioe/vscode-fold-unfold-all-icone#2]
Would it be possible to fold file by levels? like with pressing once for ex. + button folding deepest level and so on..

**Class User**
**{** <-- first level
  **function getName()**
  **{** <-- second level
    **if (isAdmin) {** <-- third level (deepest)
      **return 'Hello world';**

**Comment by Benjioe** [comment]
Hello,

It looks like what [vscode-fold-level](https://marketplace.visualstudio.com/items?itemName=vikyd.vscode-fold-level) already do ?
